version: '3'
services:
  web:
    image: "${DOCKER_REPOSITORY}:${BUILD_NUMBER}"
    restart: always
    links:
      - db
    ports:
      - 8083:8083
    network_mode: bridge
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: WebService
    ports:
    - 3306:3306
    command: --init-file /data/application/db.sql
    volumes:
    - ./init.sql:/data/application/db.sql