version: '3'
services:
  web:
    build: .
    restart: always
    links: 
      - db
    ports:
      - 8083:8083
    network_mode: bridge
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: myimage_db
      volumes:
        -dbdata: ./db.sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    network_mode: bridge